name       : python-lazy-object-proxy
version    : 1.8.0
release    : 14
source     :
    - https://github.com/ionelmc/python-lazy-object-proxy/archive/refs/tags/v1.8.0.tar.gz : 397fadb08bee0c2a359b8cc21505bb405915570b291de6a9f8224e521584a15b
homepage   : https://github.com/ionelmc/python-lazy-object-proxy
license    : BSD-2-Clause
component  : programming.python
summary    : A fast and thorough lazy object proxy
description: |
    A fast and thorough lazy object proxy.
builddeps  :
    - pkgconfig(python3)
    - python-django
    - python-pytest-benchmark
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 --ignore=src
