name       : python-lazy-object-proxy
version    : 1.7.1
release    : 11
source     :
    - https://github.com/ionelmc/python-lazy-object-proxy/archive/refs/tags/v1.7.1.tar.gz : 3dfe0846b9e90fad09e2611761270de6fefc24cdacccf29decebabca14d5711b
homepage   : https://github.com/ionelmc/python-lazy-object-proxy
license    : BSD-2-Clause
component  : programming.python
summary    : A fast and thorough lazy object proxy
description: |
    A fast and thorough lazy object proxy.
builddeps  :
    - pkgconfig(python3)
    - python-django
    - python-pytest-benchmark
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 --ignore=src
