name       : python-lazy-object-proxy
version    : 1.9.0
release    : 15
source     :
    - https://github.com/ionelmc/python-lazy-object-proxy/archive/refs/tags/v1.9.0.tar.gz : e68b22c45bf12d36aa071c7717ad3526578e4a0c8ce325421ce77d21c539fa99
homepage   : https://github.com/ionelmc/python-lazy-object-proxy
license    : BSD-2-Clause
component  : programming.python
summary    : A fast and thorough lazy object proxy
description: |
    A fast and thorough lazy object proxy.
builddeps  :
    - pkgconfig(python3)
    - python-django
    - python-pytest-benchmark
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 --ignore=src
