name       : python-lazy-object-proxy
version    : 1.3.1
release    : 2
source     :
    - https://github.com/ionelmc/python-lazy-object-proxy/archive/v1.3.1.tar.gz : b315bc589ac934feb81c954424b501bf56afdbf7851918be4261c2ccdbb14ea7
license    : BSD-2-Clause
component  : programming.python
summary    : A fast and thorough lazy object proxy.
description: |
    A fast and thorough lazy object proxy.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
