name       : python-lazy-object-proxy
version    : 1.4.3
release    : 7
source     :
    - https://github.com/ionelmc/python-lazy-object-proxy/archive/v1.4.3.tar.gz : ce4c9872869331d509ff2b7be19fdddb1dc4b922d14aa62675770e3caebd92e2
license    : BSD-2-Clause
component  : programming.python
summary    : A fast and thorough lazy object proxy.
description: |
    A fast and thorough lazy object proxy.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - python-setuptools-scm
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    # requires pytest-benchmark to be packaged.
#    %python_test pytest
#    %python3_test pytest3
